### ISSUE TITLE
In Message Store recheck if `address` can be passed as a path parameter

### ISSUE THREAD

**Issue by manuranga** [ballerina-guides/enterprise-integration-patterns#48]
Recheck if `address` can be passed as a path parameter

_Originally posted by @manuranga in https://github.com/ballerina-guides/enterprise-integration-patterns/pull/29#discussion_r1311565079_

**Comment by LakshanWeerasinghe** [comment]
@manuranga we can close this since it's updated in [line](https://github.com/ballerina-guides/enterprise-integration-patterns/blob/8f0e218ee6f8442d0a1609ae16aeef8498bb1bd5/message-store/message-store.bal#L24).

**Comment by manuranga** [comment]
Fixed in #55
